name: Deploy Images to GHCR

env:
  NODE_ENV: 'production'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Image'
            run: |
              docker build . --tag ghcr.io/requ1Re/igdb-api-proxy:latest
              docker push ghcr.io/requ1Re/igdb-api-proxy:latest